force-app/main/default/objects/Module_Response__c/Module_Response__c.object-meta.xml
<CustomObject>
    <label>Module Response</label>
    <nameField>
        <label>Module Response Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Modules Response</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Module_Response__c/fields/Module__c.field-meta.xml
<CustomField>
    <fullName>Module__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Module</label>
    <referenceTo>Module__c</referenceTo>
    <relationshipName>Modules_Answered</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Module_Response__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Modules_Response</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Unit_Response__c/Unit_Response__c.object-meta.xml
<CustomObject>
    <label>Unit Response</label>
    <nameField>
        <label>Unit Response Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Units Response</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Unit_Response__c/fields/Module_Response__c.field-meta.xml
<CustomField>
    <fullName>Module_Response__c</fullName>
    <label>Module Response</label>
    <referenceTo>Module_Response__c</referenceTo>
    <relationshipLabel>Units Response</relationshipLabel>
    <relationshipName>Units_Response</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Unit_Response__c/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Unit</label>
    <referenceTo>Unit__c</referenceTo>
    <relationshipLabel>Units Response</relationshipLabel>
    <relationshipName>Units_Response</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/User__c/User__c.object-meta.xml
<CustomObject>
    <description>Can be estudents or teachers</description>
    <label>UserTrailblazer</label>
    <nameField>
        <label>User Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Users</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/UnitService.cls
public class UnitService{
    public static Boolean registerUnitResponse(Id unitId, String jsonAnswer){

        Unit__c unit = [SELECT Module__c
                        FROM Unit__c
                        WHERE Id = :unitId];


        Module_Response__c moduleResp = new Module_Response__c(User__c = userInfo.getUserId(), Module__c = unit.Id);

        Unit_Response__c unitResp = new Unit_Response__c(Unit__c = unitId);

        insert UnitResp;
    }

}